### ISSUE TITLE
improve color support detection

### ISSUE THREAD

**Issue by ai** [nin-jin/felt-pen#1]
Can you add support for `NO_COLOR`, `FORCE_COLOR`, `--no-color`, `--color`?

**Comment by nin-jin** [comment]
No, the library should not presumptuously add new arguments to the application bypassing the application author.
There is no reason to disable coloring when TTY is supported. And there is no reason to enable coloring when TTY isn't supported.

**Comment by ai** [comment]
It will be harder for you to replace `chalk` if you will not use similar colour support detection.

But it is cool too have another philosophy in color libraries.
